name: style-transfer

on: [push]

jobs:
  run:
    runs-on: [self-hosted]
    container: 
      image: docker://dvcorg/cml-gpu-py3:latest
      options: --runtime "nvidia" -e NVIDIA_VISIBLE_DEVICES=all

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get install python3-dev -y
          pip install -r requirements.txt
          python neural_style_transfer.py imgs/owl_photo.jpg imgs/georgia_okeefe.jpg results/owl --iter 10
          
          echo "# Style transfer" >> report.md
          
          echo "## Master" >> report.md
          git show origin/master:final_owl.png > master_owl.png
          cml-publish master_owl.png --md --title 'master' >> report.md
          
          echo "## Workspace" >> report.md
          cml-publish final_owl.png --md --title 'styled' >> report.md
          
          echo "## Training metrics" >> report.md
          cat metrics.txt >> report.md
          
          echo >> report.md
          echo "## GPU info" >> report.md
          cat gpu_info.txt >> report.md
          
          cml-send-comment report.md 
          cml-send-github-check report.md 
          
